ccfri-3752, ccfri-3754, ccfri-3813 - add AFS page to Application
bcgov/EDUC-CCOF pull request #564
Opened 2024-11-08 19:59 UTC by vietle-cgi

# Description

## Types of changes

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have checked that unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

2024-11-13 23:07 UTC, weskubo-cgi requested changes

2024-11-13 23:57 UTC, vietle-cgi commented on frontend/src/utils/common.js
> +    facilityList?.findIndex((facility) => isFacilityAvailable(facility) && facility.unlockAfs && facility.enableAfs) >
great suggestion! it's updated. thank you!

2024-11-13 23:57 UTC, vietle-cgi commented on frontend/src/components/LandingPage.vue
> +      let unlockList = [];
it's updated

2024-11-13 23:57 UTC, vietle-cgi commented on frontend/src/components/LandingPage.vue
> +        this.unlockAFSList.length > 0
it's updated

2024-11-14 00:11 UTC, weskubo-cgi approved these changes

2024-11-14 00:12 UTC, merged