CCFRI-4026 - MYCCS Portal- Cannot expand second facility info in Summ…
bcgov/EDUC-CCOF pull request #587
Opened 2024-11-27 22:25 UTC by MaelCormier-CGI

…ary (The Wrong facility’s sections are expanded when trying to expand sections of the second facility on the summary page.)

# Description
Changes:
- Added a parent <v-expansion-panels> for each facility
- Added a unique key value for each <v-expansion-panel> item

## Types of changes

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have checked that unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

2024-11-28 00:43 UTC, vietle-cgi requested changes

2024-11-28 00:43 UTC, vietle-cgi commented on frontend/src/components/SummaryDeclaration.vue
> +                  <v-expansion-panels>
Hi Mael, could you also update the expandAllPanels() function to align with your new changes? The expected behavior is that if you add /printable to the end of the summary declaration URL, all panels should automatically expand.

2024-11-28 16:39 UTC, vietle-cgi requested changes

2024-11-28 16:39 UTC, vietle-cgi commented on frontend/src/components/SummaryDeclaration.vue
> +                      :key="`${facility.facilityId}-facility-information`"
I think we should use :value instead of :key

2024-11-28 16:39 UTC, vietle-cgi commented on frontend/src/components/SummaryDeclaration.vue
> +                  <v-expansion-panels>
can we add "multiple" to this one so we can open multiple panels?

2024-11-29 01:10 UTC, vietle-cgi approved these changes

2024-11-29 01:17 UTC, vietle-cgi requested changes

2024-11-29 03:01 UTC, MaelCormier-CGI commented on frontend/src/components/SummaryDeclaration.vue
> +      this.expand['global'] = ['organization-summary', 'ecewe-summary-b', 'change-notification-form-summary'];
Good catch, the value was missing. Added!

2024-11-29 06:21 UTC, vietle-cgi approved these changes

2024-11-29 17:47 UTC, merged